#default from snakemake tutorial 
#with dependencies updated according to the latest version

channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bcftools=1.5
  - bwa=0.7.12
  - graphviz=2.38.0
  - python=3.6.1
  - samtools=1.5
  - snakemake=4.0.0
  - pyyaml=3.12
  - bowtie=1.2.0

